import Header from '@/components/Header';
import './globals.css';
import './locomotive.css';
import MainLayout from '@/components/MainLayout';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body>
				<MainLayout>
					<Header />
					{children}
				</MainLayout>
			</body>
		</html>
	);
}
